-- AlterTable
ALTER TABLE "SuratMasuk" ALTER COLUMN "tanggalMasuk" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tanggalMasuk" SET DATA TYPE DATE,
ALTER COLUMN "tanggalSuratMasuk" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tanggalSuratMasuk" SET DATA TYPE DATE;
